# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='cleanrun',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deploy',
            name='idIaaS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.IaaS'),
        ),
    ]
